# Base image for ClamAV
FROM clamav/clamav:latest

# Set working directory
WORKDIR /etc/clamav

# Copy freshclam configuration to update the virus database
COPY ./freshclam.conf /etc/clamav/freshclam.conf

# Set ConcurrentDatabaseReload to no to minimize memory usage
RUN echo "ConcurrentDatabaseReload no" >> /etc/clamav/clamd.conf

# Disable Freshclam testing to minimize RAM usage
RUN echo "TestDatabases no" >> /etc/clamav/freshclam.conf

# Update the virus database
RUN freshclam

# Expose the ClamAV service port for communication
EXPOSE 3310

# Run the ClamAV daemon
CMD ["clamd", "--foreground", "--log=/var/log/clamav/clamd.log"]  # Keep clamd in the foreground for logging