version: '3'
services:
  asc606-pdf-parser:
    image: benjisho/asc606-pdf-parser:v1.0.1
    build:
      context: ./asc606-pdf-parser-app
      dockerfile: Dockerfile.pdf-parser
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse:ro  # Read-only mount
      - ./output_files:/app/output_files
    environment:
      - PYTHONUNBUFFERED=1
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true  # Make the container's filesystem read-only
    restart: unless-stopped
    depends_on:  # Ensure the ClamAV service is ready before starting the parser
      - clamav

  website:
    image: benjisho/asc606-pdf-parser-website:v1.0.1
    build:
      context: ./asc606-pdf-parser-website
      dockerfile: Dockerfile.website
    volumes:
      - ./asc606-pdf-parser-website:/app/asc606-pdf-parser-website
      - ./asc606-pdf-parser-app:/app/asc606-pdf-parser-app
      - ./pdf_files_to_parse:/app/pdf_files_to_parse
      - ./output_files:/app/output_files
    ports:
      - "5000:5000"
    restart: unless-stopped

  clamav:
    image: mkodockx/docker-clamav:latest
    volumes:
      - ./pdf_files_to_parse:/scan  # ClamAV scans files in this directory
    command: "clamd"  # Start ClamAV daemon
    restart: unless-stopped
