services:
  p2ta-pdf-parser:
    image: benjisho/p2ta-pdf-parser:v2.0.1
    build:
      context: ./p2ta-pdf-parser-app
      dockerfile: Dockerfile.pdf-parser
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse # Structure with subdirectories
      - ./output_files:/app/output_files
      - ./p2ta-pdf-parser-app/logs:/app/logs # Ensure this directory is writable on the host machine
      - type: tmpfs
        target: /app/p2ta-pdf-parser-app/logs
    environment:
      - PYTHONUNBUFFERED=1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  website:
    image: benjisho/p2ta-pdf-parser-website:v2.0.2
    build:
      context: ./p2ta-pdf-parser-website
      dockerfile: Dockerfile.website
    volumes:
      - ./p2ta-pdf-parser-website:/app/p2ta-pdf-parser-website
      - ./p2ta-pdf-parser-app:/app/p2ta-pdf-parser-app
      - ./pdf_files_to_parse:/app/pdf_files_to_parse
      - ./output_files:/app/output_files
    ports:
      - "5000:5000"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
    restart: unless-stopped
