
services:
  asc606-pdf-parser:
    image: benjisho/asc606-pdf-parser
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse:rw  # Map local directory for input PDFs
      - ./output_files:/app/output_files:rw  # Map local directory for output summaries
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is immediately flushed
    restart: unless-stopped
    # command: ["--debug"]  # Uncomment to run with debug flag if needed
