version: '3'
services:
  asc606-pdf-parser:
    image: benjisho/asc606-pdf-parser:v1.0.1
    build:
      context: ./asc606-pdf-parser-app
      dockerfile: Dockerfile.pdf-parser
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse:ro  # Read-only access to uploaded PDFs
      - ./output_files:/app/output_files:rw              # Writable access for output files only
      - ./asc606-pdf-parser-app/logs:/app/logs:rw        # Writable access for logs
    environment:
      - PYTHONUNBUFFERED=1
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true  # Keep the main file system read-only
    restart: unless-stopped

  website:
    image: benjisho/asc606-pdf-parser-website:v1.0.1
    build:
      context: ./asc606-pdf-parser-website
      dockerfile: Dockerfile.website
    volumes:
      - ./asc606-pdf-parser-website:/app/asc606-pdf-parser-website
      - ./asc606-pdf-parser-app:/app/asc606-pdf-parser-app
      - ./pdf_files_to_parse:/app/pdf_files_to_parse
      - ./output_files:/app/output_files
    ports:
      - "5000:5000"
    restart: unless-stopped
