version: '3'
services:
  asc606-pdf-parser:
    image: benjisho/asc606-pdf-parser:v1.0.1
    build:
      context: ./asc606-pdf-parser-app
      dockerfile: Dockerfile.pdf-parser
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse:ro  # Read-only mount for the parser
      - ./output_files:/app/output_files
    environment:
      - PYTHONUNBUFFERED=1
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    restart: unless-stopped
    depends_on:
      - clamav  # Ensure the ClamAV service is ready before starting the parser

  website:
    image: benjisho/asc606-pdf-parser-website:v1.0.1
    build:
      context: ./asc606-pdf-parser-website
      dockerfile: Dockerfile.website
    volumes:
      - ./asc606-pdf-parser-website:/app/asc606-pdf-parser-website
      - ./asc606-pdf-parser-app:/app/asc606-pdf-parser-app
      - ./pdf_files_to_parse:/app/pdf_files_to_parse
      - ./output_files:/app/output_files
    ports:
      - "5000:5000"
    restart: unless-stopped

  clamav:
    build:
      context: ./virus-protection/clamav
      dockerfile: Dockerfile.clamav
    volumes:
      - ./virus-protection/clamav/freshclam.conf:/etc/clamav/freshclam.conf
      - ./pdf_files_to_parse:/scan  # Directory for files to be scanned
      - ./virus-protection/clamav/clamav_logs:/var/log/clamav  # Mount ClamAV logs to a local directory
      - clamav_db:/var/lib/clamav  # Volume for ClamAV's database
    ports:
      - "3310:3310"  # Expose ClamAV daemon's port for network communication
    command: clamd --debug  # Run ClamAV in debug mode
    restart: unless-stopped

volumes:
  clamav_db:  # Persistent volume for ClamAV's database
