services:
  asc606-pdf-parser:
    image: benjisho/asc606-pdf-parser
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile to use for building the image
    volumes:
      - ./pdf_files_to_parse:/app/pdf_files_to_parse:rw  # Map local directory for input PDFs to container
      - ./output_files:/app/output_files:rw  # Map local directory for output summaries to container
    environment:
      - PYTHONUNBUFFERED=1  # Python output immediately flushed for better logging
    restart: unless-stopped  # Automatically restart the container unless it is explicitly stopped
    
    # command: ["--debug"]  # Uncomment to run with debug flag if detailed logging is needed