# Base image
FROM python:3.12.7-slim-bookworm

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update -y && apt install -y net-tools iputils-ping mtr

# Copy the requirements file
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app
COPY ./ /app/

# Expose port 5000
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "app.py"]
