# Base image
FROM python:3.12.7-slim-bookworm

# Set working directory
WORKDIR /app

RUN  apt-get update -y && apt install net-tools iputils-ping mtr -y

# Copy the requirements file for Flask
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install clamd Python library to communicate with the ClamAV daemon
RUN pip install clamd

# Copy the Flask app
COPY ./ /app/

# Expose port 5000 for Flask
EXPOSE 5000

# Command to run the Flask app
CMD ["python", "app.py"]
