name: Docker Image CI/CD

# Define the events that trigger this workflow
on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
    paths-ignore:
      - 'README.md'  # Ensure README changes don't trigger a rebuild
      - 'docker-compose.yml'  # Changes to compose file might be needed for local runs, not for Docker image builds
      - 'LICENSE'  # License changes are unlikely to affect the Docker build
      - '.dockerignore'  # Dockerignore changes generally won't affect the image content itself
      - '.gitignore'  # Gitignore changes shouldn't affect the image
      # - '.github/workflows/**'  # Changes to workflows should not trigger Docker image build
      - 'pdf_files_to_parse/**'  # Input files are dynamic and shouldn't trigger image rebuilds
      - 'output_files/**'  # Output files shouldn't trigger image rebuilds

# Define environment variables used throughout the workflow
env:
  DOCKER_IMAGE: pdf-parser  # Name of the Docker image
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Docker Hub username stored in GitHub secrets
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  # Docker Hub token stored in GitHub secrets
  DOCKER_REGISTRY: docker.io  # Docker registry URL
  IMAGE_TAG: latest  # Default tag for the image
  
# Define the job to build and publish the Docker image
jobs:
  build-and-publish:
    runs-on: ubuntu-24.04  # Use a specific version of Ubuntu for consistency

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # Action to check out the code from the repository

      # Step 2: Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Action to set up Docker Buildx

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Action to log in to Docker Hub
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Action to build and push Docker image
        with:
          context: .  # Use the current directory as the build context
          push: true  # Push the image to Docker Hub
          tags: |
            benjisho/pdf-parser:latest
            benjisho/pdf-parser:${{ github.sha }}
            benjisho/pdf-parser:${{ github.ref_name }}

      # Step 5: Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout
