name: Docker Compose Test Run

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
    paths:
      - '.github/workflows/docker_compose_test_run.yml'
      - 'p2ta-pdf-parser-app/**'
      - 'docker-compose.yml'
  pull_request:
    branches: 
      - main 
    paths:
      - '.github/workflows/docker_compose_test_run.yml'
      - 'p2ta-pdf-parser-app/**'
      - 'docker-compose.yml'

jobs:
  docker_compose_interaction_test:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Ensure Logs Directory Writable
    #   run: |
    #     mkdir -p p2ta-pdf-parser-app/logs
    #     chmod -R 777 p2ta-pdf-parser-app/logs  # Confirm writable permissions
        
    - name: Install Expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Download Sample PDF
      run: |
        wget -q -O pdf_files_to_parse/sample.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf || {
          echo "Failed to download sample PDF";
          exit 1;
        }

    - name: Pull Docker Image
      run: docker pull benjisho/p2ta-pdf-parser

    - name: Run Docker Compose with Expect
      id: run-parser
      run: |
        expect -c "
          set timeout 600
          spawn docker compose run --rm p2ta-pdf-parser --form_type asc606 --debug
          expect {
            \"No PDF files found in directory: pdf_files_to_parse\" {
              puts \"Error: No PDF files found\"
              exit 1
            }
            \"Finished extracting text from PDF\" {
              exp_continue
            }
            \"Summary written to: output_files/*\" {
              puts \"Parsing successful\"
              exit 0
            }
            default {
              puts \"Error: Parsing failed\"
              exit 1
            }
          }
        "

    - name: Stop and Remove Docker Containers (Just in case)
      run: docker compose down -v --remove-orphans

    - name: Remove Docker Image
      run: docker rmi benjisho/p2ta-pdf-parser

    timeout-minutes: 10
