name: Ubuntu Host Test Run

on:
  push:
    branches:
      - master  # Trigger workflow on pushes to the master branch
    paths:
      - '.github/workflows/ubuntu_host_test_run.yml'
      - 'p2ta-pdf-parser-app/**'
  pull_request:
    branches: 
      - master 
    paths:
      - '.github/workflows/ubuntu_host_test_run.yml'
      - 'p2ta-pdf-parser-app/**'

jobs:
  host_interaction_test:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Ensure Logs Directory Writable
    #   run: |
    #     mkdir -p p2ta-pdf-parser-app/logs
    #     chmod -R 777 p2ta-pdf-parser-app/logs  # Confirm writable permissions
        
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y wget python3 python3-pip

    - name: Install Python Requirements
      run: sudo rm /usr/lib/python*/EXTERNALLY-MANAGED && pip3 install -r p2ta-pdf-parser-app/requirements.txt
      
    - name: Download Sample PDF
      run: |
        wget -q -O pdf_files_to_parse/sample.pdf https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf || {
          echo "Failed to download sample PDF";
          exit 1;
        }

    - name: Run PDF Parser
      id: run-parser
      run: |
        python3 p2ta-pdf-parser-app/p2ta-pdf-parser.py --form_type asc606 --debug || {
          echo "Error: Parsing script failed";
          exit 1;
        }

    - name: Verify Parsing Output
      run: |
        if [ ! -f output_files/sample.txt ]; then
          echo "Error: Parsed output file not found";
          exit 1;
        else
          echo "Parsing successful: Output file generated"
        fi

    timeout-minutes: 10
